# Generated by Django 4.2.5 on 2024-02-06 23:37

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_filmwork_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
