# Generated by Django 4.2.5 on 2024-02-07 00:32

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_filmwork_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="file_path",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="file_path",
            ),
        ),
    ]
