# Generated by Django 4.2.5 on 2024-02-07 00:39

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_genre_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="film_work_id",
            new_name="film_work",
        ),
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="film_work_id",
            new_name="film_work",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="person_id",
            new_name="person",
        ),
        migrations.RemoveField(
            model_name="filmwork",
            name="genre_id",
        ),
        migrations.RemoveField(
            model_name="filmwork",
            name="person_id",
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genre",
            field=models.ManyToManyField(
                through="movies.GenreFilmWork",
                to="movies.genre",
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="person",
            field=models.ManyToManyField(
                through="movies.PersonFilmWork",
                to="movies.person",
            ),
        ),
    ]
