# Generated by Django 4.2.5 on 2024-02-08 02:34

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_rename_film_work_id_genrefilmwork_film_work_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="genre",
            new_name="genre_id",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="person",
            new_name="person_id",
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.TextField(
                choices=[("movie", "Movie"), ("tv show", "Tv Show")],
                verbose_name="Type",
            ),
        ),
    ]
