# Generated by Django 4.2.5 on 2024-02-08 09:37

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_remove_personfilmwork_film_work_person_role_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="genrefilmwork",
            name="film_work_genre_idx",
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "genre_id"),
                name="film_work_genre_ctr",
            ),
        ),
    ]
