# Generated by Django 4.2.5 on 2024-02-08 10:34

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_remove_genrefilmwork_film_work_genre_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="genrefilmwork",
            name="film_work_genre_ctr",
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["film_work_id", "genre_id"],
                name="film_work_genre_idx",
            ),
        ),
    ]
