# Generated by Django 4.2.5 on 2024-02-08 10:37

# Third Party
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0010_remove_genrefilmwork_film_work_genre_ctr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genrefilmwork",
            name="film_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movies.filmwork",
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movies.genre",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="film_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movies.filmwork",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movies.person",
            ),
        ),
    ]
