# Generated by Django 4.2.5 on 2024-03-07 09:32

# Third Party
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_alter_genrefilmwork_film_work_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                choices=[
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("writer", "Writer"),
                ],
                verbose_name="Role",
            ),
        ),
    ]
